# CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@4.0.1

jobs:
  ctrz:
    executor: aws-ecr/default
    steps:
      - checkout
      - run:
          name: "Set org and repo vars"
          command: |
            org_repo=$(git config --local remote.origin.url | sed -e 's/\.git$//' -e 's,//[^/]*/,,g' -e 's,.*:,,' -e 's#/$##' | tr '[:upper:]' '[:lower:]')
            echo 'export ORG_REPO="$org_repo"' >> $BASH_ENV
      - aws-ecr/build-and-push-image:
          create-repo: true
          repo: $ORG_REPO

workflows:
  version: 2
  build_docker_image:
    jobs:
    - ctrz:
        context: ecr
